version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-seguros-api
    restart: always
    ports:
      - "80:8000"
    volumes:
      # Mapeia a pasta local backend/data do servidor para dentro do container
      # Isso garante que o ChromaDB e os arquivos (faqs.csv) não sejam perdidos
      - ./backend/data:/app/backend/data
    env_file:
      - .env
